// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Contexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20230228092658_m1")]
    partial class m1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<double>("GreenwichDelta")
                        .HasColumnType("float")
                        .HasColumnName("GreenwichDelta");

                    b.Property<string>("GreenwichtenZamanCinsindenFarki")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GreenwichtenZamanCinsindenFarki");

                    b.Property<string>("IhlasTemkin")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IhlasTemkin");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.Property<double>("LongitudeDelta")
                        .HasColumnType("float")
                        .HasColumnName("LongitudeDelta");

                    b.Property<double>("LongitudeDeltaFromService")
                        .HasColumnType("float")
                        .HasColumnName("LongitudeDeltaFromService");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<double>("Offset")
                        .HasColumnType("float")
                        .HasColumnName("Offset");

                    b.Property<string>("SehirKisa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SehirKisa");

                    b.Property<string>("StandartBoylamQuery")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandartBoylamQuery");

                    b.Property<double>("StandartMeridian")
                        .HasColumnType("float")
                        .HasColumnName("StandartMeridian");

                    b.HasKey("Id");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DaylightSavingTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CityName");

                    b.Property<string>("End")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("End");

                    b.Property<int>("EndDiff")
                        .HasColumnType("int")
                        .HasColumnName("EndDiff");

                    b.Property<string>("Start")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Start");

                    b.Property<int?>("StartDiff")
                        .HasColumnType("int")
                        .HasColumnName("StartDiff");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("DaylightSavingTimes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PrayTime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Asr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Asr");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityId");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CityName");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("Date");

                    b.Property<string>("Fajr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Fajr");

                    b.Property<string>("Imsak")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Imsak");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Isha")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Isha");

                    b.Property<string>("Israk")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Israk");

                    b.Property<string>("Maghrib")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Maghrib");

                    b.Property<string>("Tulu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tulu");

                    b.Property<string>("Zuhr")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Zuhr");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PrayTimes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DaylightSavingTime", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("DaylightSavingTimes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.PrayTime", b =>
                {
                    b.HasOne("Domain.Entities.City", "City")
                        .WithMany("PrayTimes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Domain.Entities.City", b =>
                {
                    b.Navigation("DaylightSavingTimes");

                    b.Navigation("PrayTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
